### ISSUE TITLE
Using Flutter Stable

### ISSUE THREAD

**Issue by volkansahin45** [pass-wall/passwall-mobile#26]
I am suggesting to use Flutter Stable versions instead of `master`. `master` is so unpredictable and hard 
to follow because It is changing all the time. 

Stable versions can help us to track the status of the project and determine problems easily.

**Comment by aeosmanoglu** [comment]
After the last Flutter update, we do not need to be in master channel. I’m gonna edit the read me file. Thanx.

**Comment by aeosmanoglu** [comment]
I reopened this issue as a reminder. Thank you
