### ISSUE TITLE
I cannot connect to the server

### ISSUE THREAD

**Issue by bufgix** [pass-wall/passwall-mobile#6]
I tried demo server and own VDS but I cannot connect to the server

**Comment by yakuter** [comment]
The demo address is:

https://passwall-server.herokuapp.com

Can you try again?

**Comment by bufgix** [comment]
still same. it's like never loading just showing error
![img](https://user-images.githubusercontent.com/22038798/80085378-cebbf300-8560-11ea-962d-65eafd44eb43.png)

**Comment by aslanyi** [comment]
Did you try with https?

**Comment by aeosmanoglu** [comment]
Thank you for the feedback. Sometimes the demo server may not work. This is not a bug of the mobile application. Before testing, check if the demo server is working from your browser.
